### PR TITLE
Added Express & HTTP Server

### PR DESCRIPTION
**Pull request by RXNationGMG**
This is for replit users cause I saw this code that doesn't have a express code so, I added it. And yes, there is no errors, I've tested it and it works fine.

### CODE REVIEW

**Comment by TejasLamba2006** [comment]
Hi @RXNationGMG ,

Thank you so much for your contribution to our project! We appreciate the time and effort you put into it.

After reviewing your pull request, we suggest making the following changes:

- Please add an if statement in your code to check whether the expressServer key in the config.js file is set to true or false. Then, you can run or not run the express server based on that value.
Example
Here's an example of how you can update your config.js file:
```js
module.exports = {
  "token": process.env.TOKEN,
 "expressServer": true, //true or false boolean
  "dbType": "MONGO", //quick.db OR MONGO
  "MONGOtype": "quickmongo", //quickmongo only
  "MongoURL": "", //if dbType = MONGO, this is required else skip
  "loadSlashsGlobal": true,
  "dirSetup": [{
    "Folder": "Info", "CmdName": "info",
    "CmdDescription": "Grant specific Information about something!"
  },
              {
    "Folder": "Setup", "CmdName": "Setup",
    "CmdDescription": "Setup the welcome plugin in the server"
  }]
}
```
Here's how you can modify your code to use the updated config.js file:
```js
if (config.expressServer) {
//add the http client code here
}
```

This is necessary since not all users may use this on Replit.

If you have any questions or concerns about these changes, please do not hesitate to let us know. We appreciate any feedback you may have and look forward to your continued contributions.

Thank you again for your valuable time and effort!

Best regards,
Tejas Lamba

**Comment by RXNationGMG** [comment]
Thank you for the information, after I did that you say to add a expressServer Key I finally managed it to add it without errors, that code will be ok

> Hi @RXNationGMG ,
> 
> Thank you so much for your contribution to our project! We appreciate the time and effort you put into it.
> 
> After reviewing your pull request, we suggest making the following changes:
> 
> * Please add an if statement in your code to check whether the expressServer key in the config.js file is set to true or false. Then, you can run or not run the express server based on that value.
>   Example
>   Here's an example of how you can update your config.js file:
> 
> ```js
> module.exports = {
>   "token": process.env.TOKEN,
>  "expressServer": true, //true or false boolean
>   "dbType": "MONGO", //quick.db OR MONGO
>   "MONGOtype": "quickmongo", //quickmongo only
>   "MongoURL": "", //if dbType = MONGO, this is required else skip
>   "loadSlashsGlobal": true,
>   "dirSetup": [{
>     "Folder": "Info", "CmdName": "info",
>     "CmdDescription": "Grant specific Information about something!"
>   },
>               {
>     "Folder": "Setup", "CmdName": "Setup",
>     "CmdDescription": "Setup the welcome plugin in the server"
>   }]
> }
> ```
> 
> Here's how you can modify your code to use the updated config.js file:
> 
> ```js
> if (config.expressServer) {
> //add the http client code here
> }
> ```
> 
> This is necessary since not all users may use this on Replit.
> 
> If you have any questions or concerns about these changes, please do not hesitate to let us know. We appreciate any feedback you may have and look forward to your continued contributions.
> 
> Thank you again for your valuable time and effort!
> 
> Best regards, Tejas Lamba

**Comment by RXNationGMG** [comment]
if it has error, just ask me so I can get it fix

**Review by TejasLamba2006 — APPROVED** [review]
Seems to work

**Pull request merged**
